name: Generate requirements.txt from environment.yml

on:
  push:
    paths:
      - 'environment.yml'
  pull_request:
    paths:
      - 'environment.yml'

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.11'  # or any Python version you use in environment.yml
          auto-activate-base: false

      - name: Create Conda environment from environment.yml
        run: |
          conda env create -f environment.yml

      - name: Generate requirements.txt from environment
        run: |
          conda activate llms  # or your environment name
          pip freeze > requirements.txt

      - name: Commit the new requirements.txt
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: 'Update requirements.txt'
